name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *' # Update setiap jam
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime Stats
        uses: athul/waka-readme@latest

        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIME: "true"
          SHOW_TOTAL: "true"
          COMMIT_MESSAGE: "Update WakaTime stats"
